import Header from "@/components/Header";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Hero from "@/components/Hero";
import Cryptos from "@/components/Cryptos";
import WhyTrade from "@/components/WhyTrade";
import Registration from "@/components/Registration";
import EventGallery from "@/components/EventGallery";
import Features from "@/components/Features";
import Footer from "@/components/Footer";

const MainContainer = styled.div`
  width: 100%;
  position: relative;
`;

const GreenWorm = styled.div`
  position: absolute;
  top: 0%;
  right: 15%;
  width: 100%;
  max-width: 1067px;
  height: 1210px;
  z-index: -1;
`;

const PurpleZero = styled.div`
  position: absolute;
  top: 10%;
  left: 10%;
  width: 100%;
  max-width: 590px;
  height: 727px;
  z-index: -1;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>LP Zero Swaps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <Hero />
        <MainContainer>
          <GreenWorm>
            <Image
              alt="green vector"
              src={"/images/greenWorm.png"}
              fill
              style={{ objectFit: "contain" }}
            />
          </GreenWorm>
          <PurpleZero>
            <Image
              alt="purple zero"
              src={"/images/purpleZero.png"}
              fill
              style={{ objectFit: "contain" }}
            />
          </PurpleZero>
          <Cryptos />
          <WhyTrade />
          <Registration />
        </MainContainer>
        <EventGallery />
        <Features />
        <Footer />
      </>
    </>
  );
}
