import Header from "@/components/Header";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Hero from "@/components/Hero";
import Cryptos from "@/components/Cryptos";
import WhyTrade from "@/components/WhyTrade";
import Registration from "@/components/Registration";
import EventGallery from "@/components/EventGallery";
import Features from "@/components/Features";
import Footer from "@/components/Footer";

const MainContainer = styled.div`
  width: 100%;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>LP Zero Swaps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />

        <Hero />
        <MainContainer>
          <Cryptos />
          <WhyTrade />
          <Registration />
        </MainContainer>
        <EventGallery />
        <Features />
        <Footer />
      </>
    </>
  );
}
